config/routes.rb
Rails.application.routes.draw do

authenticated :user do
  root 'projects#index', as: :authenticated_root
end
  resources :projects do
      resources :lists do
        post :complete
        delete :del_completed
        delete :all_del_completed
        post :completed_restore
      end
  end
  resources :abouts
  # resources :lists do
  #   post :complete
  #   delete :del_completed
  #   delete :all_del_completed
  #   post :completed_restore
  # end
  devise_for :users
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :priority
  belongs_to :project
  
  require 'time_difference'
  acts_as_paranoid
  validate :check

  def check
    if startdate != nil && dateline != nil
      if dateline < startdate
        errors.add(:ไม่สามารถสร้างรายการได้, "โปรดเลือกวันเริ่มต้นก่อนวันสิ้นสุด")
      end
    end
  end

  def priority_with_name
    if self.priority_id != nil
      return "#{priority.name}"
    else
      return "ไม่ได้ระบุความสำคัญ"
    end
  end

  def priority_color
    if self.priority_id == 1
      return "rgba(233, 63, 63, 0.7)"
    elsif self.priority_id == 2
      return 'rgba(238, 164, 38, 0.7)'
    elsif self.priority_id == 3
      return 'rgba(69, 207, 212, 0.7)'
    end
  end

  def show_startdate
    if self.startdate != nil && self.startdate != ''
      return "#{self.startdate.strftime("%A %d-%B-%Y")}"
    else
      return "ไม่ได้ระบุวันเริ่มต้น"
    end
  end

  def show_dateline
    if self.dateline != nil  && self.dateline != ''
      return "#{self.dateline.strftime("%A %d-%B-%Y")}"
    else
      return "ไม่ได้ระบุวันสิ้นสุด"
    end
  end

  def cal_remain_date
    if self.startdate != nil && self.dateline != nil
      @remain_date = (self.dateline - Date.today).to_i + 1
      if @remain_date < 0
        return "เกินเวลากำหนด"
      else
        return "#{@remain_date} วัน"
      end
    else
      return "ไม่ได้กำหนดวันเริ่มต้น และ วันสิ้นสุด"
    end
  end

  def dateline_notification_color
    if cal_remain_date.to_i == 0 || cal_remain_date.to_i < 0
      return 'label label-danger glyphicon glyphicon-bell'
    elsif cal_remain_date.to_i == 1
       return 'label label-danger glyphicon glyphicon-bell'
    elsif cal_remain_date.to_i == 2
      return 'label label-warning glyphicon glyphicon-bell'
    else
      return ''
    end
  end

  def dateline_notification_text
    if cal_remain_date.to_i == 0  || cal_remain_date.to_i < 0
      return "เลยกำหนดเวลาแล้ว"
    elsif cal_remain_date.to_i  == 1
       return "ถึงกำหนดเวลาแล้ว"
    elsif cal_remain_date.to_i == 2
      return "ใกล้ถึงกำหนดแล้ว"
    else
      return
    end
  end
end

app/models/priority.rb
class Priority < ApplicationRecord
  has_many :lists
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :lists
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lists
  has_many :projects

  def name_email
    if self.name != nil && self.name != ""
      return "#{self.name}"
    else
      return  "#{self.email}"
    end
  end


end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    projects_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password, :current_password , :password_confirmation , :name) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
# before_action :authenticate_user!
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user , only: [:show , :edit , :destroy]

  def index
    @project = Project.find(params[:project_id])
    @lists = List.where(user_id: current_user.id , deleted_at:nil , status: 'incompleted' , project_id: @project).order('priority_id ASC').includes(:priority)
    @count = List.where(user_id: current_user.id , status: 'incompleted' , project_id: @project).count
    @complete_list = List.only_deleted.where(user_id: current_user.id , status: 'completed' , project_id: @project)
    @complete_count = List.only_deleted.where(user_id: current_user.id , status: 'completed' , project_id: @project).count
  end

  def new
    @list = current_user.lists.build
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    @list = current_user.lists.build(list_params)
    if @list.save && @project.save
      redirect_to  project_lists_path
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to project_lists_path
    else
      render 'edit'
    end
  end

  def complete
    @project = Project.find(params[:project_id])
    @list = List.find(params[:list_id]).destroy.update(status: 'completed')
    redirect_to project_lists_path
  end

  def all_del_completed
    @project = Project.find(params[:project_id])
    List.only_deleted.where(user_id: current_user.id , status: "completed").delete_all

    redirect_to project_lists_path
  end

  def del_completed
    @project = Project.find(params[:project_id])
    @list = List.only_deleted.find(params[:list_id])
    if @list.really_destroy!
      redirect_to project_lists_path
    end
  end

  def completed_restore
    @project = Project.find(params[:project_id])
    @list = List.only_deleted.find(params[:list_id]).update(status: 'incompleted' , deleted_at: nil)
    redirect_to project_lists_path
  end

  def show
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    if @list.really_destroy!
      redirect_to project_lists_path
    else
      render project_lists_path
    end
  end

  private
    def list_params
      params.require(:list).permit(:title , :description , :startdate  , :dateline , :priority_id , :priorities_id , :project_id)
    end
end

def correct_user
  @lists = current_user.lists.find_by(id: params[:id])
  redirect_to project_lists_path if @lists.nil?
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.where(user_id: current_user.id)
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to projects_path
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to projects_path
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path
    end
  end

  def show
    @project = Project.find(params[:id])
    @lists = List.where(project_id: @project , user_id: current_user.id)
  end

  private
    def project_params
      params.require(:project).permit(:name , :description)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/abouts/index.html.erb
<div class="jumbotron text-center">
  <h1><i class="fa fa-newspaper-o" aria-hidden="true"></i> เกี่ยวกับเรา</h1>

  <div class="row top-margin-about">
    <h2>จะนำมาใช้ได้จากที่ไหน</h2>
    <p>
      มีท่อนต่างๆ ของ Lorem Ipsum ให้หยิบมาใช้งานได้มากมาย แต่ส่วนใหญ่แล้วจะถูกนำไปปรับให้เป็นรูปแบบอื่นๆ อาจจะด้วยการสอดแทรกมุกตลก หรือด้วยคำที่มั่วขึ้นมาซึ่งถึงอย่างไรก็ไม่มีทางเป็นเรื่องจริงได้เลยแม้แต่น้อย ถ้าคุณกำลังคิดจะใช้ Lorem Ipsum สักท่อนหนึ่ง คุณจำเป็นจะต้องตรวจให้แน่ใจว่าไม่มีอะไรน่าอับอายซ่อนอยู่ภายในท่อนนั้นๆ ตัวสร้าง Lorem Ipsum บนอินเทอร์เน็ตทุกตัวมักจะเอาท่อนที่แน่ใจแล้วมาใช้ซ้ำๆ ทำให้กลายเป็นที่มาของตัวสร้างที่แท้จริงบนอินเทอร์เน็ต ในการสร้าง Lorem Ipsum ที่ดูเข้าท่า ต้องใช้คำจากพจนานุกรมภาษาละตินถึงกว่า 200 คำ ผสมกับรูปแบบโครงสร้างประโยคอีกจำนวนหนึ่ง เพราะฉะนั้น Lorem Ipsum ที่ถูกสร้างขึ้นใหม่นี้ก็จะไม่ซ้ำไปซ้ำมา ไม่มีมุกตลกซุกแฝงไว้ภายใน หรือไม่มีคำใดๆ ที่ไม่บ่งบอกความหมาย
    </p>
  </div>

  <div class="row top-margin-about">
    <div class="col-md-6">
      <h2>Lorem Ipsum คืออะไร</h2>
      <p>
        rem Ipsum คือ เนื้อหาจำลองแบบเรียบๆ ที่ใช้กันในธุรกิจงานพิมพ์หรืองานเรียงพิมพ์ มันได้กลายมาเป็นเนื้อหาจำลองมาตรฐานของธุรกิจดังกล่าวมาตั้งแต่ศตวรรษที่ 16 เมื่อเครื่องพิมพ์โนเนมเครื่องหนึ่งนำรางตัวพิมพ์มาสลับสับตำแหน่งตัวอักษรเพื่อทำหนังสือตัวอย่าง Lorem Ipsum อยู่ยงคงกระพันมาไม่ใช่แค่เพียงห้าศตวรรษ แต่อยู่มาจนถึงยุคที่พลิกโฉมเข้าสู่งานเรียงพิมพ์ด้วยวิธีทางอิเล็กทรอนิกส์ และยังคงสภาพเดิมไว้อย่างไม่มีการเปลี่ยนแปลง มันได้รับความนิยมมากขึ้นในยุค ค.ศ. 1960 เมื่อแผ่น Letraset วางจำหน่ายโดยมีข้อความบนนั้นเป็น Lorem Ipsum และล่าสุดกว่านั้น คือเมื่อซอฟท์แวร์การทำสื่อสิ่งพิมพ์ (Desktop
      </p>
    </div>

    <div class="col-md-6">
      <img src="https://dummyimage.com/800x300/000/fff.jpg" >
    </div>
  </div>

  <div class="row top-margin-about">
    <div class="col-md-6">
      <img src="https://dummyimage.com/800x300/000/fff.jpg">
    </div>
    <div class="col-md-6">
      <h2>ทำไมจึงต้องนำมาใช้?</h2>
      <p>
        มีหลักฐานที่เป็นข้อเท็จจริงยืนยันมานานแล้ว ว่าเนื้อหาที่อ่านรู้เรื่องนั้นจะไปกวนสมาธิของคนอ่านให้เขวไปจากส่วนที้เป็น Layout เรานำ Lorem Ipsum มาใช้เพราะความที่มันมีการกระจายของตัวอักษรธรรมดาๆ แบบพอประมาณ ซึ่งเอามาใช้แทนการเขียนว่า ‘ตรงนี้เป็นเนื้อหา, ตรงนี้เป็นเนื้อหา' ได้ และยังทำให้มองดูเหมือนกับภาษาอังกฤษที่อ่านได้ปกติ ปัจจุบันมีแพ็กเกจของซอฟท์แวร์การทำสื่อสิ่งพิมพ์ และซอฟท์แวร์การสร้างเว็บเพจ (Web Page Editor) หลายตัวที่ใช้ Lorem Ipsum เป็นแบบจำลองเนื้อหาที่เป็นค่าตั้งต้น และเวลาที่เสิร์ชด้วยคำว่า 'lorem ipsum' ผลการเสิร์ชที่ได้ก็จะไม่พบบรรดาเว็บไซต์ที่ยังคงอยู่ในช่วงเริ่มสร้างด้วย โดยหลายปีที่ผ่านมาก็มีการคิดค้นเวอร์ชั่นต่างๆ ของ Lorem Ipsum ขึ้นมาใช้ บ้างก็เป็นความบังเอิญ บ้างก็เป็นความตั้งใจ (เช่น การแอบแทรกมุกตลก)
      </p>
    </div>
  </div>


  <div class="row top-margin-about">
    <div class="col-md-12">
      <%= link_to 'เข้าร่วมกับเรา' , new_user_registration_path , class: 'btn btn-success btn-block' %>
      <%= link_to 'กลับ' , root_path , class: 'btn btn-default btn-block' %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <% if user_signed_in? %>
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <h2>ยินดีต้องรับคุณ  <%= current_user.name_email %></h2>
        <p>
          ขอให้มีความสุขกับการใช้งานระบบ TODO
        </p>
        <p>
          <%= link_to 'TODO LIST' , lists_path , class: 'btn btn-success' %>
        </p>
      </div>
    </div>
  </div>
  <% else %>
  <div class="row">
    <div class="col-md-6">
      <div class="jumbotron">
        <h2>สร้างรายการ TODO</h2>
        <p>
          เข้าร่วมกับเราเพื่อสร้างรายการ "ที่ต้องทำ" แบบง่ายๆ
        </p>
        <p>
          <%= link_to "เข้าร่วมกับเรา" , new_user_registration_path , class: 'btn btn-primary'  %>
          <%= link_to "ลงชื่อเข้าใช้งาน" , new_user_session_path , class: 'btn btn-success' %>
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="jumbotron">
        <h2>ทดสอบ</h2>
        <p>
          ทดสอบ
        </p>
        <p>
          <%= link_to "เข้าร่วมกับเรา" , new_user_registration_path , class: 'btn btn-primary'  %>
          <%= link_to "ลงชื่อเข้าใช้งาน" , new_user_session_path , class: 'btn btn-success' %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo Lists</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- fonts -->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Prompt">

    <!-- icon -->
    <link rel="shortcut icon" href="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/sign-check-icon.png">

    <!-- SEO -->
    <meta name="description" content="todolist">
    <meta name="author" content="Taweesak Intaratat">
    <meta name="keywords" content="web application , todolist , hobby dev">
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <% if user_signed_in? %>
              <%= link_to 'TODO' , projects_path , class: 'navbar-brand' %>
            <% else %>
              <%= link_to 'TODO' , root_path , class: 'navbar-brand' %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">

            <% if user_signed_in? %>
              <li><a href="<%= projects_path	 %>"><i class="fa fa-bars" aria-hidden="true"></i> โครงการทั้งหมด</a></li>
              <li><a href="<%= edit_user_registration_path %>"><i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= current_user.name_email %></a></li>
              <li><%= link_to " ออกจากระบบ", destroy_user_session_path ,method: :delete , class: 'fa fa-sign-out' %></li>
            <% else %>
              <li><a href="<%= new_user_registration_path %>"><i class="fa fa-user-circle" aria-hidden="true"></i> สมัครสมาชิก</a></li>
              <li><a href="<%= new_user_session_path %>"><i class="fa fa-sign-in" aria-hidden="true"></i> ลงชื่อเข้าใช้</a></li>
              <li><a href="<%= abouts_path %>"><i class="fa fa-newspaper-o" aria-hidden="true"></i> เกี่ยวกับเรา</a></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container-fluid margintop80px marginbottom80px">
      <%= yield %>
    </div>

    <div class="container-fluid">
      <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container-fluid">
          <p class="navbar-text pull-right"><i class="fa fa-copyright" aria-hidden="true"></i>2017 - Make With <span class="glyphicon glyphicon-heart redheart"></span> By
            <a href="https://github.com/game1095" target="_blank" >Game1095</a>
          </p>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for [@project , @list] do |f| %>
<% if @list.errors.any? %>
<div id="errors_explimination">
  <ul>
    <% @list.errors.full_messages.each do |msg| %>
    <li class="alert alert-danger"><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :หัวข้อเรื่อง %>
      <%= f.text_field :title , class: 'form-control' , required: true ,  autocomplete: :off  , placeholder: 'กรอกหัวข้อเรื่อง' %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :ความสำคัญ %>
      <%= f.collection_select :priority_id, Priority.all, :id, :name, {prompt: "โปรดเลือกระดับความสำคัญ"}, {class: "form-control"}%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <%= f.label :ชื่อโครงการ %>
      <%= f.collection_select :project_id , Project.where(id: @project) , :id , :name ,{ selected: Project.where(id: @project) } , {class: 'form-control'} %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :คำอธิบาย %>
  <%= f.text_area :description  , class: 'form-control' , required: true , placeholder: 'กรอกคำอธิบาย' , cols: 50 , rows: 18 %>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :วันเริ่มต้น %>
      <%= f.date_field :startdate , class: 'form-control' , required: true , min: Time.now %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :วันสิ้นสุด %>
      <%= f.date_field :dateline , class: 'form-control' ,required: true , min: Time.now  %>
    </div>
  </div>
</div>
<hr>
<div class="action pull-right">
  <%= f.submit  'บันทึก' , class: 'btn btn-success'  %>
  <%= link_to ' กลับ' , project_lists_path , class: 'btn btn-default' %>
</div>
<% end %>


<!-- <script type="text/javascript">
$(function(){

var startDate = $('#list_startdate').datepicker({
minDate: 0,
dateFormat: 'dd-mm-yy'
});

var endDate = $('#list_dateline').datepicker({
minDate: 0,
dateFormat: 'dd-mm-yy'
});

});
</script> -->

app/views/lists/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-info">
  <div class="panel panel-heading">
    <h1>แก้ไขรายการ TODO</h1>
  </div>
    <div class="panel panel-body">
      <%=render 'form' %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="col-md-12">
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4><i class="fa fa-bars" aria-hidden="true"></i> รายการ TODO</h4>
        <p>จำนวน TODO list ทั้งหมด  : <%= @count %></p>
      </div>
      <div class="panel-body">
        <div class="row bottom-margin-list">
          <div class="col-md-12">
            <div class="col-md-4">
              <%=link_to 'เพิ่มรายการ TODO' , new_project_list_path , class: 'btn btn-info btn-lg' %>
            </div>
            <div class="col-md-4 col-md-offset-4">
              <%= link_to 'กลับ' , projects_path , class: 'btn btn-default btn-lg float-right' %>
            </div>
          </div>
        </div>
        <% @lists.each do |list| %>
          <div class="col-md-6">
            <div class="well well-lg">
              <div class="row">
                <div class="col-md-8">
                  <p class="text-completed"><b>หัวข้อเรื่อง : </b><%= list.title %> </p>
                  <p><b>ความสำคัญ : </b> <span class="label" style="background-color: <%= list.priority_color %>"><%=list.priority_with_name %></span></p>
                  <p><b>เวลาที่เหลือ : </b><%= list.cal_remain_date %></p>
                  <p><b>ผู้ใช้</b> : <%= list.user.name_email %></p>
                </div>
                <div class="col-md-3">
                  <p><span class="<%= list.dateline_notification_color %>" %><%= list.dateline_notification_text %></span></p>
                </div>
              </div>
              <div class="right">
                <%=link_to " ทำเสร็จแล้ว" , project_list_complete_path(@project.id , list) , method: :post , class: 'fa fa-check-square-o btn btn-success'  %>
                <%=link_to " แก้ไข" , edit_project_list_path(@project.id , list) , class: 'fa fa-pencil-square-o btn btn-default' %>
                <%=link_to " ลบ" ,  project_list_path(@project.id , list) , method: :delete  , class: 'fa fa-trash-o btn btn-danger' , data: {confirm: 'ท่านแน่ใจหรือว่าจะลบรายการนี้ ?'} %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4><i class="fa fa-check-square-o" aria-hidden="true"></i></span> สิ่งที่ทำเสร็จแล้ว</h4>
        <p>จำนวน TODO list ที่ทำเสร็จทั้งหมด : <%= @complete_count %></p>
      </div>
      <div class="panel-body">
        <% @complete_list.each do |list| %>
            <p class="complete-warp">
              <b>หัวข้อเรื่อง</b> : <%= list.title %> <%= link_to 'ลบ' , project_list_del_completed_path(@project.id , list) , method: :delete , data: {confirm: 'ท่านแน่ใจหรือว่าจะลบรายการที่ทำเสร็จแล้ว ?'} %>
              <%= link_to 'นำกลับ' , project_list_completed_restore_path(@project.id , list) , method: :post %>
            </p>
            <hr>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
  <div class="panel panel-heading">
    <h1>เพิ่มรายการ TODO</h1>
  </div>
    <div class="panel panel-body">
      <%=render 'form' %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="panel panel-info" >
  <div class="panel-heading"><h3 class="text-center warp-show"><b>หัวข้อเรื่อง</b> : <%= @list.title %></h3></div>
  <div class="panel-body">
    <p class="warp-show"><b>คำอธิบาย</b> : <%= @list.description %></p>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <p><b>วันเริ่มต้น</b> : <%= @list.show_startdate  %></p>
        <p><b>วันสิ้นสุด</b> : <%= @list.show_dateline %></p>
        <p><b>เวลาที่เหลือ</b> : <%= @list.cal_remain_date %> </p>
      </div>
      <div class="col-md-6">
        <p><b>ผู้ใช้งาน</b> : <%= @list.user.name_email %></p>
        <p><b>ความสำคัญ : </b><span class="label" style="background-color: <%= @list.priority_color %>"><%=@list.priority_with_name %></span></p>
      </div>
    </div>
    <hr>
    <%= link_to " กลับ" , project_lists_path , class: 'pull-right fa fa-chevron-left btn btn-default' %>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :ชื่อโครงการ %>
    <%= f.text_field :name , class: 'form-control' , required: true %>
  </div>

  <div class="form-group">
    <%= f.label :คำอธิบาย %>
    <%= f.text_area :description , class: 'form-control' , required: true %>
  </div>

  <div class="form-group float-right">
    <%= f.submit 'บันทึก' ,  class: 'btn btn-success'%>
    <%= link_to 'กลับ' , projects_path , class: 'btn btn-default' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="col-md-12">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3><i class="fa fa-book" aria-hidden="true"></i> รายการโปค</h3>
      </div>
      <div class="panel-body">
        <div class="row bottom-margin-list">
          <div class="col-md-12">
            <div class="col-md-4">
              <%=link_to 'เพิ่มโปรเจค' , new_project_path , class: 'btn btn-info btn-lg' %>
            </div>
            <div class="col-md-4 col-md-offset-4">
              <!-- <%= link_to 'กลับ' , projects_path , class: 'btn btn-default btn-lg float-right' %> -->
            </div>
          </div>
        </div>
        <% @projects.each do |project| %>
          <div class="col-md-4">
            <div class="well well-lg">
              <div class="row">
                <div class="col-md-8">
                  <p class="text-completed"><b>ชื่อโปรเจค : </b><%= link_to project.name , project_lists_path(project) %></p>
                  <p class="text-completed"><b>รายละเอียด : </b><%= project.description %></p>
                </div>
                <div class="col-md-3">
                </div>
              </div>
              <div class="right">
                <%= link_to 'แก้ไข' , edit_project_path(project) , class: 'btn btn-default' %>
                <%= link_to 'ลบ' , project_path(project) , method: :delete , class: 'btn btn-danger' , data:  {confirm: 'คุณต้องการจะลบโปรเจคนี้ใช่หรือไม่ ?'}%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<h1>show</h1>
<p><%= @project.name %></p>
<% @lists.each do |list| %>
  <%= list.title %>

<% end %>

app/views/todo/index.html.erb
<div class="col-md-12">
  <div class="col-md-9">
    <h3>TODO list</h3>
    <% @lists.each do |list| %>
      <div class="jumbotron">
        <p>Title: <%= list.title %></p>
        <p>Description: <%= list.description %></p>
        <p>Finish Date : <%= list.finishedDate %></p>
        <p>User: <%= list.user.email %></p>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <h3>Completed</h3>
    <% @lists.each do |list| %>
        <p>Title: <%= list.title %></p>
    <% end %>
  </div>
</div>